### ISSUE TITLE
Bug while creating indicators

### ISSUE THREAD

**Issue by krmaxwell** [iDefense/ti-export#19]
```
Traceback (most recent call last):
  File "ti-stix2.py", line 175, in <module>
    main()
  File "ti-stix2.py", line 165, in main
    bundle = outputstix2(results, config)
  File "ti-stix2.py", line 95, in outputstix2
    pattern="[url:value='%s']" % result['key'])
  File "/Users/kyle.r.maxwell/.virtualenvs/intelgraph/lib/python3.7/site-packages/stix2/v21/sdo.py", line 207, in __init__
    super(Indicator, self).__init__(*args, **kwargs)
  File "/Users/kyle.r.maxwell/.virtualenvs/intelgraph/lib/python3.7/site-packages/stix2/base.py", line 195, in __init__
    raise MissingPropertiesError(cls, missing_kwargs)
stix2.exceptions.MissingPropertiesError: No values for required properties for Indicator: (pattern_type).
```

**Comment by krmaxwell** [comment]
STIX 2.1 spec for Indicator:
```
The pattern language used in this indicator.

The value for this property SHOULD come from the pattern-type-ov open vocabulary.

The value of this property MUST match the type of pattern data included in the pattern property.
```
